### PR TITLE
write to transaction json

### PR DESCRIPTION
**Pull request by samelamin**

### CODE REVIEW

**Comment by samelamin** [comment]
Fix for https://github.com/samelamin/spark-bigquery/issues/12

**Comment by lnicalo** [comment]
Tested on my side. Thank you.

**Comment by selamin** [comment]
@lnicalo you are most welcome! I really would appreciate it if you can rate the package when you get a chance

**Comment by samelamin** [comment]
@lnicalo you are most welcome! I really would appreciate it if you can rate the package when you get a chance

**Pull request merged**
