### PR TITLE
Don't clear the entire ENV when running EnvHacker

### LINKED ISSUE #16: setBigQueryDatasetLocation break YARN mode
Thanks for the library, seems to be working great! 

I ran into a very odd issue that took me far too long to figure out.  I'm running Spark 2.1 on Qubole (on AWS) and after getting everything working (my query would complete, etc) was still having the job fail at the end with a particularly odd error:

```
org.apache.spark.SparkException: YarnSparkHadoopUtil is not available in non-YARN mode!
    at org.apache.spark.deploy.yarn.YarnSparkHadoopUtil$.get(YarnSparkHadoopUtil.scala:131)
    at org.apache.spark.deploy.yarn.YarnRMClient.getAttemptId(YarnRMClient.scala:96)
    at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply$mcV$sp(ApplicationMaster.scala:220)
    at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:216)
    at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ShutdownHookManager.scala:188)
    at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:188)
    at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:188)
    at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1994)
    at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply$mcV$sp(ShutdownHookManager.scala:188)
    at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:188)
    at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:188)
    at scala.util.Try$.apply(Try.scala:192)
    at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:188)
    at org.apache.spark.util.SparkShutdownHookManager$$anon$2.run(ShutdownHookManager.scala:178)
    at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)
```

Doing some binary search commenting out of code to figure out where the problem was and I narrowed it down to this line:

```scala
spark.sqlContext.setBigQueryDatasetLocation(bqConfig.getString("datasetLocation"))
```

(note that config value resolves to `"US"` which should also be the default)

Removing that line and everything stays in YARN mode and works just fine.  Given that the default works fine for my use-case I didn't spend more time tracking down what might be going on, but figured I'd report the issue. 

Thanks again!

### PR DESCRIPTION
**Pull request by vijaykramesh**
This fixes https://github.com/samelamin/spark-bigquery/issues/16

There were two issues: 

First, you were running a `map.clear()` that caused things to lose a `SPARK_YARN_MODE` ENV var that [is used by spark to tell things it's in YARN mode](https://github.com/apache/spark/blob/master/resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/YarnSparkHadoopUtil.scala#L126).

Second, by converting the ENV vars to strings (instead of the internal Variable type) subsequent calls to `sys.env.get` would break, e.g. [in the spark UI](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/ui/UIUtils.scala#L150)

This PR fixes both, following the basic idea in [this stackoverflow answer](http://stackoverflow.com/questions/318239/how-do-i-set-environment-variables-from-java/19040660#19040660).  I've verified the library now works in both YARN mode and in non-YARN mode (the former running on Qubole, the latter running spark locally via docker).

Tests also pass locally for me:

```
vramesh@DB-MBP-SMG8WL:~/oss/spark-bigquery (vijay/fix_yarn)$ sbt test
[info] Loading project definition from /Users/vramesh/oss/spark-bigquery/project
[info] Set current project to spark-bigquery (in build file:/Users/vramesh/oss/spark-bigquery/)
[warn] Credentials file /Users/vramesh/.ivy2/.sbtcredentials does not exist
[info] Compiling 1 Scala source to /Users/vramesh/oss/spark-bigquery/target/scala-2.11/classes...
17/05/09 11:49:08 WARN SparkContext: Support for Java 7 is deprecated as of Spark 2.0.0
17/05/09 11:49:09 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/05/09 11:49:10 WARN SparkContext: Using an existing SparkContext; some configuration may not take effect.
[info] BigQueryClientSpecs:
[info] Scenario: When writing to BQ
[info] Scenario: When reading from BQ
17/05/09 11:49:13 WARN SparkContext: Support for Java 7 is deprecated as of Spark 2.0.0
17/05/09 11:49:13 WARN SparkContext: Using an existing SparkContext; some configuration may not take effect.
[info] BigQuerySchemaSpecs:
[info] Feature: Schema Converters. Dataframe To BQ Schema
[info]   Scenario: When converting a simple dataframe
[info]     Given A dataframe
[info]     When Passing the schema to the converter
[info]     Then We should receive a BQ Table Schema
[info]   Scenario: When converting a complex dataframe with nested data
[info]     Given A dataframe
[info]     When Passing the schema to the converter
[info]     Then We should receive a BQ Table Schema
[info]   Scenario: When converting from more obscure types
[info]     Given A dataframe
[info]     When Passing the schema to the converter
[info]     Then We should receive a BQ Table Schema
[info] ScalaCheck
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] ScalaTest
[info] Run completed in 5 seconds, 647 milliseconds.
[info] Total number of tests run: 5
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 5, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 5, Failed 0, Errors 0, Passed 5
[success] Total time: 11 s, completed May 9, 2017 11:49:14 AM
```

### CODE REVIEW

**Comment by samelamin** [comment]
Thanks alot @vijaykramesh, incidentally that is exactly where I got the envhacker code from

**Comment by samelamin** [comment]
I will deploy this later this evening

**Comment by vijaykramesh** [comment]
I somewhat guessed that's where you pulled the EnvHacker stuff from after looking through that thread on stackoverflow

Also in other small world/big data news, I've been following the airflow testing discussions that you've been leading, thanks for trying to corral people around that!

thanks again!

**Comment by samelamin** [comment]
You are absolutely welcome, we def need some sort of industry standard and this is our humble attempt at trying to create something. I added you to the email thread so please get involved!

**Pull request merged**
