### PR TITLE
Fix #56: Exception when biQuerySelect Returns Zero Rows

### LINKED ISSUE #56: Exception when biQuerySelect Returns Zero Rows
I am getting the below exception when the bigquery select returns zero records

Exception in thread "main" java.lang.UnsupportedOperationException: empty collection
	at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1370)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.first(RDD.scala:1367)
	at com.samelamin.spark.bigquery.BigQuerySQLContext.bigQuerySelect(BigQuerySQLContext.scala:92)

### PR DESCRIPTION
**Pull request by sujeet100**
This pull requests fixed the bug #56
When bigquery returns empty result then the bigQuerySelect throws an exception while trying to figure out the schema.

Check if data is empty before converting dataframe using schema else return empty dataframe.
the isEmpty() check cannot be done directly on the RDD as it fails with serialization issue.
Hence the isEmpty() check is applied after map operation to schema.

### CODE REVIEW

**Comment by samelamin** [comment]
Thanks for the PR! 👍

**Comment by sagarkbhatt** [comment]
Is this released in latest version?

**Comment by samelamin** [comment]
It should be yes

**Comment by sagarkbhatt** [comment]
Seems like it is not released in latest version. Could you please tell which version to use?

**Comment by sujeet100** [comment]
@samelamin Seems like 0.2.6 is the latest one available in maven repo.
https://repo1.maven.org/maven2/com/github/samelamin/spark-bigquery_2.11/
Could you please publish a new version of the library?

**Comment by samelamin** [comment]
No Worries i will do that this weekend hopefully

**Pull request merged**
